---
# This playbook setup a cluster.

- name: test
  remote_user: virtuser
  become: true
  hosts: ansible
  roles:
    - hello


- name: install httpd
  remote_user: virtuser
  become: true
  hosts: ansible
  roles:
    - patch

